export const FORBIDDEN_KEYWORDS = [
  "race",
  "racial",
  "ethnicity",
  "ethnic",
  "religion",
  "religious",
  "nationality",
  "national origin",
  "political affiliation",
  "political view",
  "muslim",
  "jewish",
  "christian",
  "arab",
  "turkish",
  "syrian",
  "polish",
  "german name",
  "muslim name",
  "non-native",
  "auslander",
  "ethnie",
  "religion",
  "nationalitat",
  "herkunft",
  "politische ansicht",
  "politische einstellung",
  "muslimisch",
  "judisch",
  "christlich",
  "arabisch",
  "turkisch",
  "syrisch",
  "polnisch",
  "deutscher name",
  "muslimischer name",
  "nicht muttersprachlich",
] as const;
